sudo: false

language: python
python:
- '3.5'
- '3.6'
env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - git
    - g++-5

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

install:
    - pip install .

before_script:
    #here we could clone plmc for testing



script:
    - nosetests --exclude-dir=EVcouplings/test/external evcouplings

after_sucess:
# Change permissions for Anaconda deployment script
  - chmod +x ./deploy_anaconda.sh

deploy:
  - provider: pypi
      user: ...
      password: ...
      distributions: "sdist bdist_wheel" # Your distributions here
  - provider: script
    script: ./deploy_anaconda.sh
    on:
      tags: true
    skip_cleanup: true